In [141]:
import numpy as np
import pandas as pd

In [142]:

# Création du vecteur y (vecteur de uns)
y = np.ones(8)
print("Vecteur y:")
print(y)
print()

# Création de la matrice identité I_8
I_8 = np.eye(8)

# Création de la matrice E (nulle partout sauf E[0,7] = 1)
E = np.zeros((8, 8))
E[0, 7] = 1  # Premier ligne, dernière colonne
print("Matrice E:")
print(E)
print()

# Construction de X = I_8 + E
X = I_8 + E
print("Matrice X = I_8 + E:")
print(X)
print()

# Calcul de l'estimateur des moindres carrés
# β̂ = (X^T X)^(-1) X^T y

# Étape 1: Calculer X^T
X_T = X.T
print("X^T:")
print(X_T)
print()

# Étape 2: Calculer X^T X
X_T_X = X_T @ X
print("X^T X:")
print(X_T_X)
print()

# Étape 3: Calculer (X^T X)^(-1)
X_T_X_inv = np.linalg.inv(X_T_X)
print("(X^T X)^(-1):")
print(X_T_X_inv)
print()

# Étape 4: Calculer X^T y
X_T_y = X_T @ y
print("X^T y:")
print(X_T_y)
print()

# Étape 5: Calculer β̂ = (X^T X)^(-1) X^T y
beta_hat = X_T_X_inv @ X_T_y
print("β̂ (estimateur des moindres carrés):")
print(beta_hat)
print()

# Calcul de la somme des coefficients
somme_beta = np.sum(beta_hat)
print(f"Somme des coefficients β̂: ∑β̂ᵢ = {somme_beta}")

# Vérification alternative en une seule ligne
beta_hat_alt = np.linalg.inv(X.T @ X) @ X.T @ y
print(f"\nVérification: Somme = {np.sum(beta_hat_alt)}")

Vecteur y:
[1. 1. 1. 1. 1. 1. 1. 1.]

Matrice E:
[[0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

Matrice X = I_8 + E:
[[1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

X^T:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]]

X^T X:
[[1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 2.]]

(X^T X)^(-1):
[[ 2.  0.  0.  0.  0.  0.  0. -1

In [143]:
import numpy as np

# Création de la matrice identité I_8
I_8 = np.eye(8)

# Création de la matrice E (nulle partout sauf E[0,7] = 1)
E = np.zeros((8, 8))
E[0, 7] = 1

# Construction de X = I_8 + E
X = I_8 + E
print("Matrice X:")
print(X)
print()

# Calcul de X^T X
X_T_X = X.T @ X
print("Matrice X^T X:")
print(X_T_X)
print()

# Calcul de X^T X - I_8
M = X_T_X - I_8
print("Matrice X^T X - I_8:")
print(M)
print()

# Calcul des valeurs propres
eigenvalues = np.linalg.eigvals(M)
print("Valeurs propres de X^T X - I_8:")
for i, val in enumerate(eigenvalues):
    print(f"λ_{i+1} = {val:.10f}")
print()

# Détermination du rang
# Le rang est le nombre de valeurs propres non nulles
# On utilise une tolérance pour les erreurs numériques
tolerance = 1e-10
non_zero_eigenvalues = np.sum(np.abs(eigenvalues) > tolerance)
print(f"Nombre de valeurs propres non nulles (|λ| > {tolerance}): {non_zero_eigenvalues}")
print(f"\nRang de la matrice X^T X - I_8: {non_zero_eigenvalues}")

# Méthode alternative : utiliser np.linalg.matrix_rank
rank_numpy = np.linalg.matrix_rank(M)
print(f"\nVérification avec np.linalg.matrix_rank: {rank_numpy}")

# Affichage des valeurs propres triées par magnitude
sorted_eigenvalues = np.sort(np.abs(eigenvalues))[::-1]
print("\nValeurs propres triées par magnitude décroissante:")
for i, val in enumerate(sorted_eigenvalues):
    print(f"|λ_{i+1}| = {val:.10f}")

Matrice X:
[[1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

Matrice X^T X:
[[1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 2.]]

Matrice X^T X - I_8:
[[0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]]

Valeurs propres de X^T X - I_8:
λ_1 = -0.6180339887
λ_2 = 1.6180339887
λ_3 = 0.0000000000
λ_4 = 0.0000000000
λ_5 = 0.0000000000
λ_6 = 0.0000000000
λ_7 = 0.0000000000
λ_8 = 0.0000000000

Nombre de valeurs propres non nulles (|λ| > 1e-10): 2

Rang de la matrice X^T X - I_8: 2

Vérification avec np.li

In [144]:
df = pd.read_csv('../data/wine.csv')

In [145]:
features = df[[col for col in df.columns if col != 'quality']]
target = df['quality']

In [146]:
target

0       6
1       6
2       6
3       6
4       6
       ..
4893    6
4894    5
4895    6
4896    7
4897    6
Name: quality, Length: 4898, dtype: int64

In [147]:
features = features.to_numpy()

In [148]:
features_std = (features - np.mean(features, axis=0)) / np.std(features, axis=0, ddof=0)

In [149]:
features_std.shape

(4898, 11)

In [150]:
features_T = features.T
features_T_std = features_std.T

In [151]:
beta = np.linalg.inv(features_T_std @ features_std) @ features_T_std @ target


In [152]:
residuals = features_std @ beta - target
residuals_squared_norm = np.sum(residuals**2)

In [153]:
residuals_squared_norm

np.float64(171983.33880876756)